[package]
edition = "2024"
name = "bevy_softbody2d"
version = "0.19.1"
authors = ["Josiah Putman <joshikatsu@gmail.com>"]
description = "Bevy amoeba Bevy game engine."
documentation = "https://docs.rs/bevy_softbody2d/latest/bevy_softbody2d"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/Katsutoshii/bevy_softbody2d"
repository = "https://github.com/Katsutoshii/bevy_softbody2d"
keywords = ["bevy"]
readme = "README.md"
exclude = ["assets/*"]

[dependencies]
bevy = { version = "0.19", default-features = false, features = [
    "std",
    "bevy_asset",
    "bevy_image",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_state",
] }

[dev-dependencies]
bevy = { version = "0.19", default-features = true, features = [
    "file_watcher",
    "bevy_dev_tools",
    "embedded_watcher",
    "dynamic_linking",
] }
bevy-inspector-egui = { version = "0.37" }
bevy_egui = { version = "0.40" }

[features]
debug = []

[[example]]
name = "basic"
